-- Training Experiments Schema for SAP HANA
-- Optimized for column store with proper partitioning and indexes

-- 1. TRAINING_EXPERIMENTS - Track training runs
CREATE COLUMN TABLE "AI_TRAINING"."TRAINING_EXPERIMENTS" (
    "ID" NVARCHAR(36) PRIMARY KEY,
    "NAME" NVARCHAR(256) NOT NULL,
    "DESCRIPTION" NCLOB,
    "MODEL_ID" NVARCHAR(128) NOT NULL,
    "MODEL_VERSION" NVARCHAR(32),
    "ALGORITHM" NVARCHAR(64) NOT NULL,  -- SFT, KTO, GRPO, DAPO
    "DATASET_ID" NVARCHAR(128) NOT NULL,
    "DATASET_SIZE" INTEGER,
    "CONFIG_JSON" NCLOB,  -- Full training config
    "STATUS" NVARCHAR(32) DEFAULT 'CREATED',  -- CREATED, RUNNING, COMPLETED, FAILED, CANCELLED
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "STARTED_AT" TIMESTAMP,
    "COMPLETED_AT" TIMESTAMP,
    "CREATED_BY" NVARCHAR(128),
    "TAGS" NVARCHAR(1024)  -- Comma-separated tags
);

-- 2. TRAINING_METRICS - Time-series training metrics
CREATE COLUMN TABLE "AI_TRAINING"."TRAINING_METRICS" (
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "EXPERIMENT_ID" NVARCHAR(36) NOT NULL,
    "STEP" INTEGER NOT NULL,
    "EPOCH" INTEGER,
    "TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "METRIC_NAME" NVARCHAR(64) NOT NULL,
    "METRIC_VALUE" DOUBLE,
    "METADATA_JSON" NCLOB,
    FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "AI_TRAINING"."TRAINING_EXPERIMENTS"("ID")
);

-- 3. MODEL_VERSIONS - Model versioning and registry
CREATE COLUMN TABLE "AI_TRAINING"."MODEL_VERSIONS" (
    "ID" NVARCHAR(36) PRIMARY KEY,
    "MODEL_ID" NVARCHAR(128) NOT NULL,
    "VERSION_MAJOR" INTEGER NOT NULL,
    "VERSION_MINOR" INTEGER NOT NULL,
    "VERSION_PATCH" INTEGER NOT NULL,
    "EXPERIMENT_ID" NVARCHAR(36),
    "CHECKPOINT_PATH" NVARCHAR(512),
    "METRICS_JSON" NCLOB,  -- Final metrics snapshot
    "STATUS" NVARCHAR(32) DEFAULT 'DRAFT',  -- DRAFT, STAGING, PRODUCTION, ARCHIVED
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "PROMOTED_AT" TIMESTAMP,
    "PROMOTED_BY" NVARCHAR(128),
    FOREIGN KEY ("EXPERIMENT_ID") REFERENCES "AI_TRAINING"."TRAINING_EXPERIMENTS"("ID")
);

-- 4. MODEL_DEPLOYMENTS - Track model deployments (A/B testing, rollback)
CREATE COLUMN TABLE "AI_TRAINING"."MODEL_DEPLOYMENTS" (
    "ID" NVARCHAR(36) PRIMARY KEY,
    "MODEL_VERSION_ID" NVARCHAR(36) NOT NULL,
    "ENVIRONMENT" NVARCHAR(32) NOT NULL,  -- DEV, STAGING, PRODUCTION
    "TRAFFIC_PERCENTAGE" INTEGER DEFAULT 100,
    "STATUS" NVARCHAR(32) DEFAULT 'ACTIVE',
    "DEPLOYED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "DEPLOYED_BY" NVARCHAR(128),
    "ROLLBACK_FROM_ID" NVARCHAR(36),
    FOREIGN KEY ("MODEL_VERSION_ID") REFERENCES "AI_TRAINING"."MODEL_VERSIONS"("ID")
);

-- 5. INFERENCE_METRICS - Runtime inference metrics
CREATE COLUMN TABLE "AI_TRAINING"."INFERENCE_METRICS" (
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY,
    "MODEL_VERSION_ID" NVARCHAR(36) NOT NULL,
    "TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "LATENCY_MS" DOUBLE,
    "TOKENS_IN" INTEGER,
    "TOKENS_OUT" INTEGER,
    "SUCCESS" BOOLEAN,
    "ERROR_CODE" NVARCHAR(64),
    PRIMARY KEY ("ID", "TIMESTAMP")
) PARTITION BY RANGE ("TIMESTAMP") (
    PARTITION '2026_Q1' <= '2026-04-01',
    PARTITION '2026_Q2' <= '2026-07-01',
    PARTITION '2026_Q3' <= '2026-10-01',
    PARTITION '2026_Q4' <= '2027-01-01',
    PARTITION OTHERS
);

-- 6. AUDIT_LOG - Model governance and compliance
CREATE COLUMN TABLE "AI_TRAINING"."AUDIT_LOG" (
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ACTION" NVARCHAR(64) NOT NULL,
    "ENTITY_TYPE" NVARCHAR(64) NOT NULL,
    "ENTITY_ID" NVARCHAR(36) NOT NULL,
    "USER_ID" NVARCHAR(128),
    "DETAILS_JSON" NCLOB,
    "IP_ADDRESS" NVARCHAR(45)
);

-- Create indexes for common queries
CREATE INDEX "IDX_METRICS_EXPERIMENT" ON "AI_TRAINING"."TRAINING_METRICS" ("EXPERIMENT_ID", "STEP");
CREATE INDEX "IDX_METRICS_NAME" ON "AI_TRAINING"."TRAINING_METRICS" ("METRIC_NAME");
CREATE INDEX "IDX_MODEL_VERSIONS_MODEL" ON "AI_TRAINING"."MODEL_VERSIONS" ("MODEL_ID", "VERSION_MAJOR", "VERSION_MINOR", "VERSION_PATCH");
CREATE INDEX "IDX_DEPLOYMENTS_ENV" ON "AI_TRAINING"."MODEL_DEPLOYMENTS" ("ENVIRONMENT", "STATUS");
CREATE INDEX "IDX_INFERENCE_MODEL" ON "AI_TRAINING"."INFERENCE_METRICS" ("MODEL_VERSION_ID", "TIMESTAMP");
CREATE INDEX "IDX_AUDIT_ENTITY" ON "AI_TRAINING"."AUDIT_LOG" ("ENTITY_TYPE", "ENTITY_ID");

