-- Trial Balance HANA Cloud Schema
-- Database tables for trial balance application

-- Account Master Table
CREATE COLUMN TABLE "TRIAL_BALANCE_ACCOUNTS" (
    "ACCOUNT_ID" NVARCHAR(20) NOT NULL,
    "ACCOUNT_NAME" NVARCHAR(200) NOT NULL,
    "ACCOUNT_TYPE" NVARCHAR(50) NOT NULL, -- Asset, Liability, Equity, Revenue, Expense
    "ACCOUNT_GROUP" NVARCHAR(100),
    "COMPANY_CODE" NVARCHAR(10) NOT NULL,
    "COST_CENTER" NVARCHAR(20),
    "CURRENCY" NVARCHAR(3) DEFAULT 'USD',
    "IS_ACTIVE" BOOLEAN DEFAULT TRUE,
    "CREATED_BY" NVARCHAR(100),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "MODIFIED_BY" NVARCHAR(100),
    "MODIFIED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ACCOUNT_ID", "COMPANY_CODE")
);

-- Trial Balance Entries Table
CREATE COLUMN TABLE "TRIAL_BALANCE_ENTRIES" (
    "ENTRY_ID" NVARCHAR(36) NOT NULL,
    "ACCOUNT_ID" NVARCHAR(20) NOT NULL,
    "COMPANY_CODE" NVARCHAR(10) NOT NULL,
    "PERIOD" NVARCHAR(6) NOT NULL, -- YYYYMM format
    "FISCAL_YEAR" NVARCHAR(4) NOT NULL,
    "DEBIT_AMOUNT" DECIMAL(19,2) DEFAULT 0,
    "CREDIT_AMOUNT" DECIMAL(19,2) DEFAULT 0,
    "BALANCE" DECIMAL(19,2) DEFAULT 0,
    "CURRENCY" NVARCHAR(3) DEFAULT 'USD',
    "STATUS" NVARCHAR(20) DEFAULT 'DRAFT', -- DRAFT, PENDING_CHECKER, PENDING_MANAGER, APPROVED, REJECTED
    "CREATED_BY" NVARCHAR(100),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "MODIFIED_BY" NVARCHAR(100),
    "MODIFIED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ENTRY_ID")
);

-- Workflow History Table
CREATE COLUMN TABLE "TRIAL_BALANCE_WORKFLOW" (
    "WORKFLOW_ID" NVARCHAR(36) NOT NULL,
    "ENTRY_ID" NVARCHAR(36) NOT NULL,
    "STATUS" NVARCHAR(20) NOT NULL,
    "ROLE" NVARCHAR(20) NOT NULL, -- MAKER, CHECKER, MANAGER
    "USER_ID" NVARCHAR(100) NOT NULL,
    "ACTION" NVARCHAR(20) NOT NULL, -- CREATED, SUBMITTED, APPROVED, REJECTED
    "COMMENTS" NVARCHAR(500),
    "TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("WORKFLOW_ID")
);

-- Transaction Details Table
CREATE COLUMN TABLE "TRIAL_BALANCE_TRANSACTIONS" (
    "TRANSACTION_ID" NVARCHAR(36) NOT NULL,
    "ENTRY_ID" NVARCHAR(36) NOT NULL,
    "ACCOUNT_ID" NVARCHAR(20) NOT NULL,
    "COMPANY_CODE" NVARCHAR(10) NOT NULL,
    "POSTING_DATE" DATE NOT NULL,
    "DOCUMENT_NUMBER" NVARCHAR(20),
    "REFERENCE" NVARCHAR(50),
    "DEBIT_AMOUNT" DECIMAL(19,2) DEFAULT 0,
    "CREDIT_AMOUNT" DECIMAL(19,2) DEFAULT 0,
    "CURRENCY" NVARCHAR(3) DEFAULT 'USD',
    "DESCRIPTION" NVARCHAR(200),
    "CREATED_BY" NVARCHAR(100),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("TRANSACTION_ID")
);

-- Reconciliation Table
CREATE COLUMN TABLE "TRIAL_BALANCE_RECONCILIATION" (
    "RECONCILIATION_ID" NVARCHAR(36) NOT NULL,
    "ACCOUNT_ID" NVARCHAR(20) NOT NULL,
    "COMPANY_CODE" NVARCHAR(10) NOT NULL,
    "PERIOD" NVARCHAR(6) NOT NULL,
    "STATUS" NVARCHAR(20) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED
    "VARIANCE" DECIMAL(19,2),
    "AI_SUGGESTION" NCLOB,
    "RECONCILED_BY" NVARCHAR(100),
    "RECONCILED_AT" TIMESTAMP,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("RECONCILIATION_ID")
);

-- AI Narrative Table
CREATE COLUMN TABLE "TRIAL_BALANCE_NARRATIVES" (
    "NARRATIVE_ID" NVARCHAR(36) NOT NULL,
    "COMPANY_CODE" NVARCHAR(10) NOT NULL,
    "PERIOD" NVARCHAR(6) NOT NULL,
    "NARRATIVE_TYPE" NVARCHAR(50), -- SUMMARY, VARIANCE, TREND
    "NARRATIVE_TEXT" NCLOB,
    "GENERATED_BY" NVARCHAR(100), -- Service name (e.g., nLocalModels)
    "GENERATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("NARRATIVE_ID")
);

-- Create Indexes
CREATE INDEX "IDX_TB_ENTRIES_ACCOUNT" ON "TRIAL_BALANCE_ENTRIES"("ACCOUNT_ID", "COMPANY_CODE");
CREATE INDEX "IDX_TB_ENTRIES_PERIOD" ON "TRIAL_BALANCE_ENTRIES"("PERIOD", "COMPANY_CODE");
CREATE INDEX "IDX_TB_ENTRIES_STATUS" ON "TRIAL_BALANCE_ENTRIES"("STATUS");
CREATE INDEX "IDX_TB_WORKFLOW_ENTRY" ON "TRIAL_BALANCE_WORKFLOW"("ENTRY_ID");
CREATE INDEX "IDX_TB_WORKFLOW_USER" ON "TRIAL_BALANCE_WORKFLOW"("USER_ID", "STATUS");
CREATE INDEX "IDX_TB_TRANSACTIONS_ENTRY" ON "TRIAL_BALANCE_TRANSACTIONS"("ENTRY_ID");
CREATE INDEX "IDX_TB_RECONCILIATION_ACCOUNT" ON "TRIAL_BALANCE_RECONCILIATION"("ACCOUNT_ID", "PERIOD");

-- Create Foreign Key Constraints
ALTER TABLE "TRIAL_BALANCE_ENTRIES" ADD CONSTRAINT "FK_ENTRIES_ACCOUNT" 
    FOREIGN KEY ("ACCOUNT_ID", "COMPANY_CODE") 
    REFERENCES "TRIAL_BALANCE_ACCOUNTS"("ACCOUNT_ID", "COMPANY_CODE");

ALTER TABLE "TRIAL_BALANCE_WORKFLOW" ADD CONSTRAINT "FK_WORKFLOW_ENTRY" 
    FOREIGN KEY ("ENTRY_ID") 
    REFERENCES "TRIAL_BALANCE_ENTRIES"("ENTRY_ID");

ALTER TABLE "TRIAL_BALANCE_TRANSACTIONS" ADD CONSTRAINT "FK_TRANSACTIONS_ENTRY" 
    FOREIGN KEY ("ENTRY_ID") 
    REFERENCES "TRIAL_BALANCE_ENTRIES"("ENTRY_ID");